fail_fast: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff-check
        args: [--fix, "--output-format", "concise"]
      - id: ruff-format
        args: ["--output-format", "concise", "--preview"]
        types_or: [python, pyi, markdown]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.4
    hooks:
      - id: uv-lock

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    - id: pyupgrade
      args: ["--py310-plus"]
